# Site settings
title: Code Bites
#email: we-dont-have@email.yet
description: > # this means to ignore newlines until "baseurl:"
  CodeBites.co blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codebites.co" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  codebites

# Build settings
markdown: kramdown
#highlighter: pygments

